services:
  db:
    build: .
    image: bdsnowflake-lab1-db:local
    container_name: bdsnowflake_lab1_db
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      POSTGRES_DB: snowflake_lab
    ports:
      - "5432:5432"
    volumes:
      - lab1_postgres_data:/var/lib/postgresql/data

volumes:
  lab1_postgres_data:

